CREATE TABLE "SOURCE_SCHEMA"."CTI_INDICATORS"
(
    "IOC_ID" NUMBER(*,0),
    "IOC_VALUE" VARCHAR2(500),
    "IOC_TYPE" VARCHAR2(50),
    "MALWARE_FAMILY" VARCHAR2(100),
    "CONFIDENCE_SCORE" NUMBER(3,0),
    "LAST_SEEN" DATE
);
