CREATE TABLE "SOURCE_SCHEMA"."VAULT_ACCESS_AUDIT"
(
    "AUDIT_ID" NUMBER(*,0),
    "USER_PRINCIPAL" VARCHAR2(255),
    "RESOURCE_PATH" VARCHAR2(1000),
    "ACCESS_TYPE" VARCHAR2(50),
    "AUTH_METHOD" VARCHAR2(100),
    "RESPONSE_CODE" VARCHAR2(10)
);
