-- DYNAMICALLY GENERATED TEST DATA
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

-- Inserting 5 sample rows into "SOURCE_SCHEMA"."CTI_INDICATORS"
INSERT INTO "SOURCE_SCHEMA"."CTI_INDICATORS" ("IOC_ID", "IOC_VALUE", "IOC_TYPE", "MALWARE_FAMILY", "CONFIDENCE_SCORE", "LAST_SEEN") VALUES (48022, 'TEST_DATA_705', 'TEST_DATA_630', 'TEST_DATA_633', 47184, SYSDATE - 351);
INSERT INTO "SOURCE_SCHEMA"."CTI_INDICATORS" ("IOC_ID", "IOC_VALUE", "IOC_TYPE", "MALWARE_FAMILY", "CONFIDENCE_SCORE", "LAST_SEEN") VALUES (47947, 'TEST_DATA_262', 'TEST_DATA_906', 'TEST_DATA_883', 24132, SYSDATE - 290);
INSERT INTO "SOURCE_SCHEMA"."CTI_INDICATORS" ("IOC_ID", "IOC_VALUE", "IOC_TYPE", "MALWARE_FAMILY", "CONFIDENCE_SCORE", "LAST_SEEN") VALUES (14112, 'TEST_DATA_965', 'TEST_DATA_422', 'TEST_DATA_440', 50390, SYSDATE - 59);
INSERT INTO "SOURCE_SCHEMA"."CTI_INDICATORS" ("IOC_ID", "IOC_VALUE", "IOC_TYPE", "MALWARE_FAMILY", "CONFIDENCE_SCORE", "LAST_SEEN") VALUES (20419, 'TEST_DATA_328', 'TEST_DATA_605', 'TEST_DATA_800', 42980, SYSDATE - 258);
INSERT INTO "SOURCE_SCHEMA"."CTI_INDICATORS" ("IOC_ID", "IOC_VALUE", "IOC_TYPE", "MALWARE_FAMILY", "CONFIDENCE_SCORE", "LAST_SEEN") VALUES (5392, 'TEST_DATA_963', 'TEST_DATA_722', 'TEST_DATA_264', 5456, SYSDATE - 350);
COMMIT;

-- Inserting 5 sample rows into "SOURCE_SCHEMA"."HOME_GUARDIAN_CONFIG"
INSERT INTO "SOURCE_SCHEMA"."HOME_GUARDIAN_CONFIG" ("CONFIG_ID", "PARAM_NAME", "PARAM_VALUE", "IS_ENCRYPTED", "UPDATE_BY") VALUES (41098, 'TEST_DATA_156', 'TEST_DATA_781', 'TEST_DATA_274', 'TEST_DATA_709');
INSERT INTO "SOURCE_SCHEMA"."HOME_GUARDIAN_CONFIG" ("CONFIG_ID", "PARAM_NAME", "PARAM_VALUE", "IS_ENCRYPTED", "UPDATE_BY") VALUES (11550, 'TEST_DATA_607', 'TEST_DATA_270', 'TEST_DATA_339', 'TEST_DATA_709');
INSERT INTO "SOURCE_SCHEMA"."HOME_GUARDIAN_CONFIG" ("CONFIG_ID", "PARAM_NAME", "PARAM_VALUE", "IS_ENCRYPTED", "UPDATE_BY") VALUES (99669, 'TEST_DATA_273', 'TEST_DATA_141', 'TEST_DATA_204', 'TEST_DATA_219');
INSERT INTO "SOURCE_SCHEMA"."HOME_GUARDIAN_CONFIG" ("CONFIG_ID", "PARAM_NAME", "PARAM_VALUE", "IS_ENCRYPTED", "UPDATE_BY") VALUES (95386, 'TEST_DATA_315', 'TEST_DATA_398', 'TEST_DATA_162', 'TEST_DATA_686');
INSERT INTO "SOURCE_SCHEMA"."HOME_GUARDIAN_CONFIG" ("CONFIG_ID", "PARAM_NAME", "PARAM_VALUE", "IS_ENCRYPTED", "UPDATE_BY") VALUES (91463, 'TEST_DATA_528', 'TEST_DATA_621', 'TEST_DATA_921', 'TEST_DATA_448');
COMMIT;

-- Inserting 5 sample rows into "SOURCE_SCHEMA"."SENTINEL_THREAT_LOGS"
INSERT INTO "SOURCE_SCHEMA"."SENTINEL_THREAT_LOGS" ("LOG_ID", "DETECTION_TIME", "THREAT_LEVEL", "SOURCE_IP", "THREAT_DESCRIPTION", "MITIGATION_STATUS") VALUES (84038, SYSDATE - 51, 'TEST_DATA_589', 'TEST_DATA_305', 'TEST_DATA_671', 'TEST_DATA_796');
INSERT INTO "SOURCE_SCHEMA"."SENTINEL_THREAT_LOGS" ("LOG_ID", "DETECTION_TIME", "THREAT_LEVEL", "SOURCE_IP", "THREAT_DESCRIPTION", "MITIGATION_STATUS") VALUES (55801, SYSDATE - 226, 'TEST_DATA_786', 'TEST_DATA_732', 'TEST_DATA_415', 'TEST_DATA_868');
INSERT INTO "SOURCE_SCHEMA"."SENTINEL_THREAT_LOGS" ("LOG_ID", "DETECTION_TIME", "THREAT_LEVEL", "SOURCE_IP", "THREAT_DESCRIPTION", "MITIGATION_STATUS") VALUES (74476, SYSDATE - 89, 'TEST_DATA_935', 'TEST_DATA_991', 'TEST_DATA_207', 'TEST_DATA_567');
INSERT INTO "SOURCE_SCHEMA"."SENTINEL_THREAT_LOGS" ("LOG_ID", "DETECTION_TIME", "THREAT_LEVEL", "SOURCE_IP", "THREAT_DESCRIPTION", "MITIGATION_STATUS") VALUES (1097, SYSDATE - 32, 'TEST_DATA_435', 'TEST_DATA_743', 'TEST_DATA_691', 'TEST_DATA_129');
INSERT INTO "SOURCE_SCHEMA"."SENTINEL_THREAT_LOGS" ("LOG_ID", "DETECTION_TIME", "THREAT_LEVEL", "SOURCE_IP", "THREAT_DESCRIPTION", "MITIGATION_STATUS") VALUES (52021, SYSDATE - 348, 'TEST_DATA_629', 'TEST_DATA_103', 'TEST_DATA_852', 'TEST_DATA_788');
COMMIT;

-- Inserting 5 sample rows into "SOURCE_SCHEMA"."VAULT_ACCESS_AUDIT"
INSERT INTO "SOURCE_SCHEMA"."VAULT_ACCESS_AUDIT" ("AUDIT_ID", "USER_PRINCIPAL", "RESOURCE_PATH", "ACCESS_TYPE", "AUTH_METHOD", "RESPONSE_CODE") VALUES (80507, 'TEST_DATA_433', 'TEST_DATA_908', 'TEST_DATA_301', 'TEST_DATA_527', 'TEST_DATA_864');
INSERT INTO "SOURCE_SCHEMA"."VAULT_ACCESS_AUDIT" ("AUDIT_ID", "USER_PRINCIPAL", "RESOURCE_PATH", "ACCESS_TYPE", "AUTH_METHOD", "RESPONSE_CODE") VALUES (70382, 'TEST_DATA_342', 'TEST_DATA_597', 'TEST_DATA_758', 'TEST_DATA_377', 'TEST_DATA_438');
INSERT INTO "SOURCE_SCHEMA"."VAULT_ACCESS_AUDIT" ("AUDIT_ID", "USER_PRINCIPAL", "RESOURCE_PATH", "ACCESS_TYPE", "AUTH_METHOD", "RESPONSE_CODE") VALUES (81856, 'TEST_DATA_526', 'TEST_DATA_422', 'TEST_DATA_463', 'TEST_DATA_935', 'TEST_DATA_335');
INSERT INTO "SOURCE_SCHEMA"."VAULT_ACCESS_AUDIT" ("AUDIT_ID", "USER_PRINCIPAL", "RESOURCE_PATH", "ACCESS_TYPE", "AUTH_METHOD", "RESPONSE_CODE") VALUES (76275, 'TEST_DATA_918', 'TEST_DATA_860', 'TEST_DATA_762', 'TEST_DATA_727', 'TEST_DATA_816');
INSERT INTO "SOURCE_SCHEMA"."VAULT_ACCESS_AUDIT" ("AUDIT_ID", "USER_PRINCIPAL", "RESOURCE_PATH", "ACCESS_TYPE", "AUTH_METHOD", "RESPONSE_CODE") VALUES (67218, 'TEST_DATA_231', 'TEST_DATA_886', 'TEST_DATA_316', 'TEST_DATA_284', 'TEST_DATA_264');
COMMIT;
