-- ROLLBACK SCRIPT: SOURCE_SCHEMA
SET ECHO ON;

DROP TABLE "SOURCE_SCHEMA"."CTI_INDICATORS" CASCADE CONSTRAINTS;
DROP TABLE "SOURCE_SCHEMA"."HOME_GUARDIAN_CONFIG" CASCADE CONSTRAINTS;
DROP TABLE "SOURCE_SCHEMA"."SENTINEL_THREAT_LOGS" CASCADE CONSTRAINTS;
DROP TABLE "SOURCE_SCHEMA"."VAULT_ACCESS_AUDIT" CASCADE CONSTRAINTS;
COMMIT;
EXIT;