-- ROLLBACK SCRIPT: TARGET_SCHEMA
SET ECHO ON;

DROP TABLE "TARGET_SCHEMA"."APP_SYNC_STATS" CASCADE CONSTRAINTS;
DROP TABLE "TARGET_SCHEMA"."TEST_CTI_INDICATORS" CASCADE CONSTRAINTS;
DROP TABLE "TARGET_SCHEMA"."TEST_HOME_GUARDIAN_CONFIG" CASCADE CONSTRAINTS;
DROP TABLE "TARGET_SCHEMA"."TEST_SENTINEL_THREAT_LOGS" CASCADE CONSTRAINTS;
DROP TABLE "TARGET_SCHEMA"."TEST_VAULT_ACCESS_AUDIT" CASCADE CONSTRAINTS;
DROP VIEW "TARGET_SCHEMA"."V_TEST_CTI_INDICATORS";
DROP VIEW "TARGET_SCHEMA"."V_TEST_HOME_GUARDIAN_CONFIG";
DROP VIEW "TARGET_SCHEMA"."V_TEST_SENTINEL_THREAT_LOGS";
DROP VIEW "TARGET_SCHEMA"."V_TEST_VAULT_ACCESS_AUDIT";
DROP PACKAGE "TARGET_SCHEMA"."PKG_AUDIT_UTILS";
DROP PACKAGE "TARGET_SCHEMA"."PKG_SENTINEL_DATA_SYNC";
BEGIN
    FOR r IN (SELECT job_name FROM all_scheduler_jobs WHERE owner = 'TARGET_SCHEMA' AND job_name = 'JOB_PRC_LOAD_CTI_INDICATORS')
    LOOP DBMS_SCHEDULER.DROP_JOB(r.job_name); END LOOP;
END;
/

BEGIN
    FOR r IN (SELECT job_name FROM all_scheduler_jobs WHERE owner = 'TARGET_SCHEMA' AND job_name = 'JOB_PRC_LOAD_HOME_GUARDIAN_CONFIG')
    LOOP DBMS_SCHEDULER.DROP_JOB(r.job_name); END LOOP;
END;
/

BEGIN
    FOR r IN (SELECT job_name FROM all_scheduler_jobs WHERE owner = 'TARGET_SCHEMA' AND job_name = 'JOB_PRC_LOAD_SENTINEL_THREAT_LOGS')
    LOOP DBMS_SCHEDULER.DROP_JOB(r.job_name); END LOOP;
END;
/

BEGIN
    FOR r IN (SELECT job_name FROM all_scheduler_jobs WHERE owner = 'TARGET_SCHEMA' AND job_name = 'JOB_PRC_LOAD_VAULT_ACCESS_AUDIT')
    LOOP DBMS_SCHEDULER.DROP_JOB(r.job_name); END LOOP;
END;
/

COMMIT;
EXIT;