CREATE TABLE "TEST_SCHEMA"."TEST_SENTINEL_THREAT_LOGS"
(
    "LOG_ID" NUMBER(*,0),
    "DETECTION_TIME" DATE,
    "THREAT_LEVEL" VARCHAR2(20),
    "SOURCE_IP" VARCHAR2(45),
    "THREAT_DESCRIPTION" VARCHAR2(4000),
    "MITIGATION_STATUS" VARCHAR2(50)
,
    "INSERTED_ON" DATE DEFAULT SYSDATE
);
