CREATE OR REPLACE PACKAGE "TARGET_SCHEMA"."PKG_AUDIT_UTILS" AS
    PROCEDURE LOG_STATS(p_table_name IN VARCHAR2, p_rows IN NUMBER, p_status IN VARCHAR2, p_error IN VARCHAR2 DEFAULT NULL);
END "PKG_AUDIT_UTILS";
/

CREATE OR REPLACE PACKAGE BODY "TARGET_SCHEMA"."PKG_AUDIT_UTILS" AS
    PROCEDURE LOG_STATS(p_table_name IN VARCHAR2, p_rows IN NUMBER, p_status IN VARCHAR2, p_error IN VARCHAR2 DEFAULT NULL) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO "APP_SYNC_STATS" (TABLE_NAME, ROWS_PROCESSED, STATUS, ERROR_MESSAGE)
        VALUES (p_table_name, p_rows, p_status, p_error);
        COMMIT;
    END LOG_STATS;
END "PKG_AUDIT_UTILS";
/