CREATE OR REPLACE PACKAGE "TARGET_SCHEMA"."PKG_SENTINEL_DATA_SYNC" AS
    PROCEDURE PRC_LOAD_CTI_INDICATORS;
    PROCEDURE PRC_LOAD_HOME_GUARDIAN_CONFIG;
    PROCEDURE PRC_LOAD_SENTINEL_THREAT_LOGS;
    PROCEDURE PRC_LOAD_VAULT_ACCESS_AUDIT;
END "PKG_SENTINEL_DATA_SYNC";
/

CREATE OR REPLACE PACKAGE BODY "TARGET_SCHEMA"."PKG_SENTINEL_DATA_SYNC" AS
    PROCEDURE PRC_LOAD_CTI_INDICATORS IS
        v_rows NUMBER;
    BEGIN
        MERGE INTO "TARGET_SCHEMA"."TEST_CTI_INDICATORS" tgt
        USING "SOURCE_SCHEMA"."CTI_INDICATORS" src
        ON (tgt.IOC_ID = src.IOC_ID AND tgt.IOC_VALUE = src.IOC_VALUE AND tgt.IOC_TYPE = src.IOC_TYPE AND tgt.MALWARE_FAMILY = src.MALWARE_FAMILY AND tgt.CONFIDENCE_SCORE = src.CONFIDENCE_SCORE AND tgt.LAST_SEEN = src.LAST_SEEN)
        WHEN MATCHED THEN
            UPDATE SET 
                tgt.IOC_ID = src.IOC_ID,
                tgt.IOC_VALUE = src.IOC_VALUE,
                tgt.IOC_TYPE = src.IOC_TYPE,
                tgt.MALWARE_FAMILY = src.MALWARE_FAMILY,
                tgt.CONFIDENCE_SCORE = src.CONFIDENCE_SCORE,
                tgt.LAST_SEEN = src.LAST_SEEN
        WHEN NOT MATCHED THEN
            INSERT (IOC_ID, IOC_VALUE, IOC_TYPE, MALWARE_FAMILY, CONFIDENCE_SCORE, LAST_SEEN)
            VALUES (src.IOC_ID, src.IOC_VALUE, src.IOC_TYPE, src.MALWARE_FAMILY, src.CONFIDENCE_SCORE, src.LAST_SEEN);
            
        v_rows := SQL%ROWCOUNT;
        
        "PKG_AUDIT_UTILS".LOG_STATS('TEST_CTI_INDICATORS', v_rows, 'SUCCESS');
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            "PKG_AUDIT_UTILS".LOG_STATS('TEST_CTI_INDICATORS', 0, 'ERROR', SQLERRM);
            ROLLBACK;
            RAISE;
    END PRC_LOAD_CTI_INDICATORS;
    PROCEDURE PRC_LOAD_HOME_GUARDIAN_CONFIG IS
        v_rows NUMBER;
    BEGIN
        MERGE INTO "TARGET_SCHEMA"."TEST_HOME_GUARDIAN_CONFIG" tgt
        USING "SOURCE_SCHEMA"."HOME_GUARDIAN_CONFIG" src
        ON (tgt.CONFIG_ID = src.CONFIG_ID AND tgt.PARAM_NAME = src.PARAM_NAME AND tgt.PARAM_VALUE = src.PARAM_VALUE AND tgt.IS_ENCRYPTED = src.IS_ENCRYPTED AND tgt.UPDATE_BY = src.UPDATE_BY)
        WHEN MATCHED THEN
            UPDATE SET 
                tgt.CONFIG_ID = src.CONFIG_ID,
                tgt.PARAM_NAME = src.PARAM_NAME,
                tgt.PARAM_VALUE = src.PARAM_VALUE,
                tgt.IS_ENCRYPTED = src.IS_ENCRYPTED,
                tgt.UPDATE_BY = src.UPDATE_BY
        WHEN NOT MATCHED THEN
            INSERT (CONFIG_ID, PARAM_NAME, PARAM_VALUE, IS_ENCRYPTED, UPDATE_BY)
            VALUES (src.CONFIG_ID, src.PARAM_NAME, src.PARAM_VALUE, src.IS_ENCRYPTED, src.UPDATE_BY);
            
        v_rows := SQL%ROWCOUNT;
        
        "PKG_AUDIT_UTILS".LOG_STATS('TEST_HOME_GUARDIAN_CONFIG', v_rows, 'SUCCESS');
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            "PKG_AUDIT_UTILS".LOG_STATS('TEST_HOME_GUARDIAN_CONFIG', 0, 'ERROR', SQLERRM);
            ROLLBACK;
            RAISE;
    END PRC_LOAD_HOME_GUARDIAN_CONFIG;
    PROCEDURE PRC_LOAD_SENTINEL_THREAT_LOGS IS
        v_rows NUMBER;
    BEGIN
        MERGE INTO "TARGET_SCHEMA"."TEST_SENTINEL_THREAT_LOGS" tgt
        USING "SOURCE_SCHEMA"."SENTINEL_THREAT_LOGS" src
        ON (tgt.LOG_ID = src.LOG_ID AND tgt.DETECTION_TIME = src.DETECTION_TIME AND tgt.THREAT_LEVEL = src.THREAT_LEVEL AND tgt.SOURCE_IP = src.SOURCE_IP AND tgt.THREAT_DESCRIPTION = src.THREAT_DESCRIPTION AND tgt.MITIGATION_STATUS = src.MITIGATION_STATUS)
        WHEN MATCHED THEN
            UPDATE SET 
                tgt.LOG_ID = src.LOG_ID,
                tgt.DETECTION_TIME = src.DETECTION_TIME,
                tgt.THREAT_LEVEL = src.THREAT_LEVEL,
                tgt.SOURCE_IP = src.SOURCE_IP,
                tgt.THREAT_DESCRIPTION = src.THREAT_DESCRIPTION,
                tgt.MITIGATION_STATUS = src.MITIGATION_STATUS
        WHEN NOT MATCHED THEN
            INSERT (LOG_ID, DETECTION_TIME, THREAT_LEVEL, SOURCE_IP, THREAT_DESCRIPTION, MITIGATION_STATUS)
            VALUES (src.LOG_ID, src.DETECTION_TIME, src.THREAT_LEVEL, src.SOURCE_IP, src.THREAT_DESCRIPTION, src.MITIGATION_STATUS);
            
        v_rows := SQL%ROWCOUNT;
        
        "PKG_AUDIT_UTILS".LOG_STATS('TEST_SENTINEL_THREAT_LOGS', v_rows, 'SUCCESS');
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            "PKG_AUDIT_UTILS".LOG_STATS('TEST_SENTINEL_THREAT_LOGS', 0, 'ERROR', SQLERRM);
            ROLLBACK;
            RAISE;
    END PRC_LOAD_SENTINEL_THREAT_LOGS;
    PROCEDURE PRC_LOAD_VAULT_ACCESS_AUDIT IS
        v_rows NUMBER;
    BEGIN
        MERGE INTO "TARGET_SCHEMA"."TEST_VAULT_ACCESS_AUDIT" tgt
        USING "SOURCE_SCHEMA"."VAULT_ACCESS_AUDIT" src
        ON (tgt.AUDIT_ID = src.AUDIT_ID AND tgt.USER_PRINCIPAL = src.USER_PRINCIPAL AND tgt.RESOURCE_PATH = src.RESOURCE_PATH AND tgt.ACCESS_TYPE = src.ACCESS_TYPE AND tgt.AUTH_METHOD = src.AUTH_METHOD AND tgt.RESPONSE_CODE = src.RESPONSE_CODE)
        WHEN MATCHED THEN
            UPDATE SET 
                tgt.AUDIT_ID = src.AUDIT_ID,
                tgt.USER_PRINCIPAL = src.USER_PRINCIPAL,
                tgt.RESOURCE_PATH = src.RESOURCE_PATH,
                tgt.ACCESS_TYPE = src.ACCESS_TYPE,
                tgt.AUTH_METHOD = src.AUTH_METHOD,
                tgt.RESPONSE_CODE = src.RESPONSE_CODE
        WHEN NOT MATCHED THEN
            INSERT (AUDIT_ID, USER_PRINCIPAL, RESOURCE_PATH, ACCESS_TYPE, AUTH_METHOD, RESPONSE_CODE)
            VALUES (src.AUDIT_ID, src.USER_PRINCIPAL, src.RESOURCE_PATH, src.ACCESS_TYPE, src.AUTH_METHOD, src.RESPONSE_CODE);
            
        v_rows := SQL%ROWCOUNT;
        
        "PKG_AUDIT_UTILS".LOG_STATS('TEST_VAULT_ACCESS_AUDIT', v_rows, 'SUCCESS');
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            "PKG_AUDIT_UTILS".LOG_STATS('TEST_VAULT_ACCESS_AUDIT', 0, 'ERROR', SQLERRM);
            ROLLBACK;
            RAISE;
    END PRC_LOAD_VAULT_ACCESS_AUDIT;
END "PKG_SENTINEL_DATA_SYNC";
/