CREATE TABLE "SENTINEL_THREAT_LOGS"
(
    "LOG_ID" NUMBER(*,0),
    "DETECTION_TIME" DATE,
    "THREAT_LEVEL" VARCHAR2(20),
    "SOURCE_IP" VARCHAR2(45),
    "THREAT_DESCRIPTION" VARCHAR2(4000),
    "MITIGATION_STATUS" VARCHAR2(50)
)
/
CREATE TABLE "CTI_INDICATORS"
(
    "IOC_ID" NUMBER(*,0),
    "IOC_VALUE" VARCHAR2(500),
    "IOC_TYPE" VARCHAR2(50),
    "MALWARE_FAMILY" VARCHAR2(100),
    "CONFIDENCE_SCORE" NUMBER(3,0),
    "LAST_SEEN" DATE
)
/
CREATE TABLE "VAULT_ACCESS_AUDIT"
(
    "AUDIT_ID" NUMBER(*,0),
    "USER_PRINCIPAL" VARCHAR2(255),
    "RESOURCE_PATH" VARCHAR2(1000),
    "ACCESS_TYPE" VARCHAR2(50),
    "AUTH_METHOD" VARCHAR2(100),
    "RESPONSE_CODE" VARCHAR2(10)
)
/
CREATE TABLE "HOME_GUARDIAN_CONFIG"
(
    "CONFIG_ID" NUMBER(*,0),
    "PARAM_NAME" VARCHAR2(255),
    "PARAM_VALUE" VARCHAR2(1000),
    "IS_ENCRYPTED" VARCHAR2(1),
    "UPDATE_BY" VARCHAR2(100)
)
/