CREATE TABLE "TARGET_SCHEMA"."TEST_HOME_GUARDIAN_CONFIG"
(
    "CONFIG_ID" NUMBER(*,0),
    "PARAM_NAME" VARCHAR2(255),
    "PARAM_VALUE" VARCHAR2(1000),
    "IS_ENCRYPTED" VARCHAR2(1),
    "UPDATE_BY" VARCHAR2(100)
)
/;
